// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bin_data_cpp
IntegerVector bin_data_cpp(NumericVector x, NumericVector breaks, bool include_lowest);
RcppExport SEXP _dataprep_bin_data_cpp(SEXP xSEXP, SEXP breaksSEXP, SEXP include_lowestSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type breaks(breaksSEXP);
    Rcpp::traits::input_parameter< bool >::type include_lowest(include_lowestSEXP);
    rcpp_result_gen = Rcpp::wrap(bin_data_cpp(x, breaks, include_lowest));
    return rcpp_result_gen;
END_RCPP
}
// condextr_cpp
List condextr_cpp(NumericVector time_sec, IntegerVector group_int, NumericMatrix x, double step_sec, double half, double threshold_sec, double top, double toperr, double topmag, double bottom, double boterr, double botmag, int interval, int times, int n_threads);
RcppExport SEXP _dataprep_condextr_cpp(SEXP time_secSEXP, SEXP group_intSEXP, SEXP xSEXP, SEXP step_secSEXP, SEXP halfSEXP, SEXP threshold_secSEXP, SEXP topSEXP, SEXP toperrSEXP, SEXP topmagSEXP, SEXP bottomSEXP, SEXP boterrSEXP, SEXP botmagSEXP, SEXP intervalSEXP, SEXP timesSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time_sec(time_secSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_int(group_intSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type step_sec(step_secSEXP);
    Rcpp::traits::input_parameter< double >::type half(halfSEXP);
    Rcpp::traits::input_parameter< double >::type threshold_sec(threshold_secSEXP);
    Rcpp::traits::input_parameter< double >::type top(topSEXP);
    Rcpp::traits::input_parameter< double >::type toperr(toperrSEXP);
    Rcpp::traits::input_parameter< double >::type topmag(topmagSEXP);
    Rcpp::traits::input_parameter< double >::type bottom(bottomSEXP);
    Rcpp::traits::input_parameter< double >::type boterr(boterrSEXP);
    Rcpp::traits::input_parameter< double >::type botmag(botmagSEXP);
    Rcpp::traits::input_parameter< int >::type interval(intervalSEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(condextr_cpp(time_sec, group_int, x, step_sec, half, threshold_sec, top, toperr, topmag, bottom, boterr, botmag, interval, times, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// create_lags_cpp
NumericMatrix create_lags_cpp(NumericMatrix x, IntegerVector group, IntegerVector lags, bool fill_na);
RcppExport SEXP _dataprep_create_lags_cpp(SEXP xSEXP, SEXP groupSEXP, SEXP lagsSEXP, SEXP fill_naSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< bool >::type fill_na(fill_naSEXP);
    rcpp_result_gen = Rcpp::wrap(create_lags_cpp(x, group, lags, fill_na));
    return rcpp_result_gen;
END_RCPP
}
// dcast_cpp
SEXP dcast_cpp(SEXP data, SEXP id, SEXP variable, SEXP value, SEXP variable_name, int cores, SEXP fill, bool na_rm);
RcppExport SEXP _dataprep_dcast_cpp(SEXP dataSEXP, SEXP idSEXP, SEXP variableSEXP, SEXP valueSEXP, SEXP variable_nameSEXP, SEXP coresSEXP, SEXP fillSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type id(idSEXP);
    Rcpp::traits::input_parameter< SEXP >::type variable(variableSEXP);
    Rcpp::traits::input_parameter< SEXP >::type value(valueSEXP);
    Rcpp::traits::input_parameter< SEXP >::type variable_name(variable_nameSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fill(fillSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(dcast_cpp(data, id, variable, value, variable_name, cores, fill, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// desc_stats_cpp
NumericMatrix desc_stats_cpp(NumericMatrix x, IntegerVector stats_idx, int n_threads);
RcppExport SEXP _dataprep_desc_stats_cpp(SEXP xSEXP, SEXP stats_idxSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type stats_idx(stats_idxSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(desc_stats_cpp(x, stats_idx, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// detect_outliers_cpp
LogicalVector detect_outliers_cpp(NumericVector x, std::string method, double top, double bottom, double coef);
RcppExport SEXP _dataprep_detect_outliers_cpp(SEXP xSEXP, SEXP methodSEXP, SEXP topSEXP, SEXP bottomSEXP, SEXP coefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type top(topSEXP);
    Rcpp::traits::input_parameter< double >::type bottom(bottomSEXP);
    Rcpp::traits::input_parameter< double >::type coef(coefSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_outliers_cpp(x, method, top, bottom, coef));
    return rcpp_result_gen;
END_RCPP
}
// detect_outliers_matrix_cpp
LogicalMatrix detect_outliers_matrix_cpp(NumericMatrix x, std::string method, double top, double bottom, double coef);
RcppExport SEXP _dataprep_detect_outliers_matrix_cpp(SEXP xSEXP, SEXP methodSEXP, SEXP topSEXP, SEXP bottomSEXP, SEXP coefSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type top(topSEXP);
    Rcpp::traits::input_parameter< double >::type bottom(bottomSEXP);
    Rcpp::traits::input_parameter< double >::type coef(coefSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_outliers_matrix_cpp(x, method, top, bottom, coef));
    return rcpp_result_gen;
END_RCPP
}
// filter_high_cor_cpp
LogicalVector filter_high_cor_cpp(NumericMatrix x, double cutoff, bool keep_first);
RcppExport SEXP _dataprep_filter_high_cor_cpp(SEXP xSEXP, SEXP cutoffSEXP, SEXP keep_firstSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_first(keep_firstSEXP);
    rcpp_result_gen = Rcpp::wrap(filter_high_cor_cpp(x, cutoff, keep_first));
    return rcpp_result_gen;
END_RCPP
}
// filter_low_var_cpp
LogicalVector filter_low_var_cpp(NumericMatrix x, double cutoff, bool use_sd);
RcppExport SEXP _dataprep_filter_low_var_cpp(SEXP xSEXP, SEXP cutoffSEXP, SEXP use_sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< bool >::type use_sd(use_sdSEXP);
    rcpp_result_gen = Rcpp::wrap(filter_low_var_cpp(x, cutoff, use_sd));
    return rcpp_result_gen;
END_RCPP
}
// impute_cpp
NumericVector impute_cpp(NumericVector x, std::string method);
RcppExport SEXP _dataprep_impute_cpp(SEXP xSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(impute_cpp(x, method));
    return rcpp_result_gen;
END_RCPP
}
// impute_matrix_cpp
NumericMatrix impute_matrix_cpp(NumericMatrix x, std::string method);
RcppExport SEXP _dataprep_impute_matrix_cpp(SEXP xSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(impute_matrix_cpp(x, method));
    return rcpp_result_gen;
END_RCPP
}
// lin_interp_cpp
NumericVector lin_interp_cpp(NumericVector x);
RcppExport SEXP _dataprep_lin_interp_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(lin_interp_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// lin_interp_matrix_cpp
NumericMatrix lin_interp_matrix_cpp(NumericMatrix x);
RcppExport SEXP _dataprep_lin_interp_matrix_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(lin_interp_matrix_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// log_returns_cpp
NumericVector log_returns_cpp(NumericVector x);
RcppExport SEXP _dataprep_log_returns_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(log_returns_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// mark_outliers_cpp
NumericVector mark_outliers_cpp(NumericVector x, double top, double toperr, double topmag, double bottom, double boterr, double botmag, bool use_threshold_error);
RcppExport SEXP _dataprep_mark_outliers_cpp(SEXP xSEXP, SEXP topSEXP, SEXP toperrSEXP, SEXP topmagSEXP, SEXP bottomSEXP, SEXP boterrSEXP, SEXP botmagSEXP, SEXP use_threshold_errorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type top(topSEXP);
    Rcpp::traits::input_parameter< double >::type toperr(toperrSEXP);
    Rcpp::traits::input_parameter< double >::type topmag(topmagSEXP);
    Rcpp::traits::input_parameter< double >::type bottom(bottomSEXP);
    Rcpp::traits::input_parameter< double >::type boterr(boterrSEXP);
    Rcpp::traits::input_parameter< double >::type botmag(botmagSEXP);
    Rcpp::traits::input_parameter< bool >::type use_threshold_error(use_threshold_errorSEXP);
    rcpp_result_gen = Rcpp::wrap(mark_outliers_cpp(x, top, toperr, topmag, bottom, boterr, botmag, use_threshold_error));
    return rcpp_result_gen;
END_RCPP
}
// mark_outliers_matrix_cpp
NumericMatrix mark_outliers_matrix_cpp(NumericMatrix mat, double top, double toperr, double topmag, double bottom, double boterr, double botmag, bool use_threshold_error, int n_threads);
RcppExport SEXP _dataprep_mark_outliers_matrix_cpp(SEXP matSEXP, SEXP topSEXP, SEXP toperrSEXP, SEXP topmagSEXP, SEXP bottomSEXP, SEXP boterrSEXP, SEXP botmagSEXP, SEXP use_threshold_errorSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< double >::type top(topSEXP);
    Rcpp::traits::input_parameter< double >::type toperr(toperrSEXP);
    Rcpp::traits::input_parameter< double >::type topmag(topmagSEXP);
    Rcpp::traits::input_parameter< double >::type bottom(bottomSEXP);
    Rcpp::traits::input_parameter< double >::type boterr(boterrSEXP);
    Rcpp::traits::input_parameter< double >::type botmag(botmagSEXP);
    Rcpp::traits::input_parameter< bool >::type use_threshold_error(use_threshold_errorSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mark_outliers_matrix_cpp(mat, top, toperr, topmag, bottom, boterr, botmag, use_threshold_error, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// melt_cpp
SEXP melt_cpp(SEXP df, SEXP id, SEXP variable_name, SEXP value_name, SEXP major, bool as_factor, int n_threads, bool na_rm);
RcppExport SEXP _dataprep_melt_cpp(SEXP dfSEXP, SEXP idSEXP, SEXP variable_nameSEXP, SEXP value_nameSEXP, SEXP majorSEXP, SEXP as_factorSEXP, SEXP n_threadsSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type df(dfSEXP);
    Rcpp::traits::input_parameter< SEXP >::type id(idSEXP);
    Rcpp::traits::input_parameter< SEXP >::type variable_name(variable_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type value_name(value_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type major(majorSEXP);
    Rcpp::traits::input_parameter< bool >::type as_factor(as_factorSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(melt_cpp(df, id, variable_name, value_name, major, as_factor, n_threads, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// na_frac_cpp
NumericVector na_frac_cpp(NumericMatrix x);
RcppExport SEXP _dataprep_na_frac_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(na_frac_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// na_runs_cpp
List na_runs_cpp(NumericVector x);
RcppExport SEXP _dataprep_na_runs_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(na_runs_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// obsedele_cpp
LogicalVector obsedele_cpp(NumericVector time_sec, IntegerVector group_int, NumericMatrix x, double step_sec, double half, double threshold_sec, int n_threads);
RcppExport SEXP _dataprep_obsedele_cpp(SEXP time_secSEXP, SEXP group_intSEXP, SEXP xSEXP, SEXP step_secSEXP, SEXP halfSEXP, SEXP threshold_secSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time_sec(time_secSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_int(group_intSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type step_sec(step_secSEXP);
    Rcpp::traits::input_parameter< double >::type half(halfSEXP);
    Rcpp::traits::input_parameter< double >::type threshold_sec(threshold_secSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(obsedele_cpp(time_sec, group_int, x, step_sec, half, threshold_sec, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// quantile_cpp
NumericVector quantile_cpp(NumericVector x, NumericVector probs);
RcppExport SEXP _dataprep_quantile_cpp(SEXP xSEXP, SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(quantile_cpp(x, probs));
    return rcpp_result_gen;
END_RCPP
}
// roll_stats_cpp
NumericVector roll_stats_cpp(NumericVector x, int window, std::string method);
RcppExport SEXP _dataprep_roll_stats_cpp(SEXP xSEXP, SEXP windowSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(roll_stats_cpp(x, window, method));
    return rcpp_result_gen;
END_RCPP
}
// shorvalu_fill_cpp
void shorvalu_fill_cpp(NumericMatrix x, IntegerVector starts, IntegerVector lens, int n_threads);
RcppExport SEXP _dataprep_shorvalu_fill_cpp(SEXP xSEXP, SEXP startsSEXP, SEXP lensSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type lens(lensSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    shorvalu_fill_cpp(x, starts, lens, n_threads);
    return R_NilValue;
END_RCPP
}
// shorvalu_segment_cpp
List shorvalu_segment_cpp(NumericVector time_sec, double intervals_sec);
RcppExport SEXP _dataprep_shorvalu_segment_cpp(SEXP time_secSEXP, SEXP intervals_secSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time_sec(time_secSEXP);
    Rcpp::traits::input_parameter< double >::type intervals_sec(intervals_secSEXP);
    rcpp_result_gen = Rcpp::wrap(shorvalu_segment_cpp(time_sec, intervals_sec));
    return rcpp_result_gen;
END_RCPP
}
// snr_cpp
NumericVector snr_cpp(NumericMatrix x);
RcppExport SEXP _dataprep_snr_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(snr_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// transform_elem_cpp
NumericVector transform_elem_cpp(NumericVector x, std::string method, double lambda);
RcppExport SEXP _dataprep_transform_elem_cpp(SEXP xSEXP, SEXP methodSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(transform_elem_cpp(x, method, lambda));
    return rcpp_result_gen;
END_RCPP
}
// transform_scale_cpp
NumericVector transform_scale_cpp(NumericVector x, std::string method);
RcppExport SEXP _dataprep_transform_scale_cpp(SEXP xSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(transform_scale_cpp(x, method));
    return rcpp_result_gen;
END_RCPP
}
// winsorize_cpp
NumericVector winsorize_cpp(NumericVector x, double top, double bottom);
RcppExport SEXP _dataprep_winsorize_cpp(SEXP xSEXP, SEXP topSEXP, SEXP bottomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type top(topSEXP);
    Rcpp::traits::input_parameter< double >::type bottom(bottomSEXP);
    rcpp_result_gen = Rcpp::wrap(winsorize_cpp(x, top, bottom));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dataprep_bin_data_cpp", (DL_FUNC) &_dataprep_bin_data_cpp, 3},
    {"_dataprep_condextr_cpp", (DL_FUNC) &_dataprep_condextr_cpp, 15},
    {"_dataprep_create_lags_cpp", (DL_FUNC) &_dataprep_create_lags_cpp, 4},
    {"_dataprep_dcast_cpp", (DL_FUNC) &_dataprep_dcast_cpp, 8},
    {"_dataprep_desc_stats_cpp", (DL_FUNC) &_dataprep_desc_stats_cpp, 3},
    {"_dataprep_detect_outliers_cpp", (DL_FUNC) &_dataprep_detect_outliers_cpp, 5},
    {"_dataprep_detect_outliers_matrix_cpp", (DL_FUNC) &_dataprep_detect_outliers_matrix_cpp, 5},
    {"_dataprep_filter_high_cor_cpp", (DL_FUNC) &_dataprep_filter_high_cor_cpp, 3},
    {"_dataprep_filter_low_var_cpp", (DL_FUNC) &_dataprep_filter_low_var_cpp, 3},
    {"_dataprep_impute_cpp", (DL_FUNC) &_dataprep_impute_cpp, 2},
    {"_dataprep_impute_matrix_cpp", (DL_FUNC) &_dataprep_impute_matrix_cpp, 2},
    {"_dataprep_lin_interp_cpp", (DL_FUNC) &_dataprep_lin_interp_cpp, 1},
    {"_dataprep_lin_interp_matrix_cpp", (DL_FUNC) &_dataprep_lin_interp_matrix_cpp, 1},
    {"_dataprep_log_returns_cpp", (DL_FUNC) &_dataprep_log_returns_cpp, 1},
    {"_dataprep_mark_outliers_cpp", (DL_FUNC) &_dataprep_mark_outliers_cpp, 8},
    {"_dataprep_mark_outliers_matrix_cpp", (DL_FUNC) &_dataprep_mark_outliers_matrix_cpp, 9},
    {"_dataprep_melt_cpp", (DL_FUNC) &_dataprep_melt_cpp, 8},
    {"_dataprep_na_frac_cpp", (DL_FUNC) &_dataprep_na_frac_cpp, 1},
    {"_dataprep_na_runs_cpp", (DL_FUNC) &_dataprep_na_runs_cpp, 1},
    {"_dataprep_obsedele_cpp", (DL_FUNC) &_dataprep_obsedele_cpp, 7},
    {"_dataprep_quantile_cpp", (DL_FUNC) &_dataprep_quantile_cpp, 2},
    {"_dataprep_roll_stats_cpp", (DL_FUNC) &_dataprep_roll_stats_cpp, 3},
    {"_dataprep_shorvalu_fill_cpp", (DL_FUNC) &_dataprep_shorvalu_fill_cpp, 4},
    {"_dataprep_shorvalu_segment_cpp", (DL_FUNC) &_dataprep_shorvalu_segment_cpp, 2},
    {"_dataprep_snr_cpp", (DL_FUNC) &_dataprep_snr_cpp, 1},
    {"_dataprep_transform_elem_cpp", (DL_FUNC) &_dataprep_transform_elem_cpp, 3},
    {"_dataprep_transform_scale_cpp", (DL_FUNC) &_dataprep_transform_scale_cpp, 2},
    {"_dataprep_winsorize_cpp", (DL_FUNC) &_dataprep_winsorize_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_dataprep(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
