# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bin_data_cpp <- function(x, breaks, include_lowest = TRUE) {
    .Call(`_dataprep_bin_data_cpp`, x, breaks, include_lowest)
}

condextr_cpp <- function(time_sec, group_int, x, step_sec, half, threshold_sec, top, toperr, topmag, bottom, boterr, botmag, interval, times, n_threads = 0L) {
    .Call(`_dataprep_condextr_cpp`, time_sec, group_int, x, step_sec, half, threshold_sec, top, toperr, topmag, bottom, boterr, botmag, interval, times, n_threads)
}

create_lags_cpp <- function(x, group, lags, fill_na = TRUE) {
    .Call(`_dataprep_create_lags_cpp`, x, group, lags, fill_na)
}

dcast_cpp <- function(data, id = NULL, variable = NULL, value = NULL, variable_name = NULL, cores = 0L, fill = NULL, na_rm = FALSE) {
    .Call(`_dataprep_dcast_cpp`, data, id, variable, value, variable_name, cores, fill, na_rm)
}

desc_stats_cpp <- function(x, stats_idx, n_threads = 0L) {
    .Call(`_dataprep_desc_stats_cpp`, x, stats_idx, n_threads)
}

detect_outliers_cpp <- function(x, method, top, bottom, coef) {
    .Call(`_dataprep_detect_outliers_cpp`, x, method, top, bottom, coef)
}

detect_outliers_matrix_cpp <- function(x, method, top, bottom, coef) {
    .Call(`_dataprep_detect_outliers_matrix_cpp`, x, method, top, bottom, coef)
}

filter_high_cor_cpp <- function(x, cutoff, keep_first = TRUE) {
    .Call(`_dataprep_filter_high_cor_cpp`, x, cutoff, keep_first)
}

filter_low_var_cpp <- function(x, cutoff, use_sd = FALSE) {
    .Call(`_dataprep_filter_low_var_cpp`, x, cutoff, use_sd)
}

impute_cpp <- function(x, method) {
    .Call(`_dataprep_impute_cpp`, x, method)
}

impute_matrix_cpp <- function(x, method) {
    .Call(`_dataprep_impute_matrix_cpp`, x, method)
}

lin_interp_cpp <- function(x) {
    .Call(`_dataprep_lin_interp_cpp`, x)
}

lin_interp_matrix_cpp <- function(x) {
    .Call(`_dataprep_lin_interp_matrix_cpp`, x)
}

log_returns_cpp <- function(x) {
    .Call(`_dataprep_log_returns_cpp`, x)
}

mark_outliers_cpp <- function(x, top, toperr, topmag, bottom, boterr, botmag, use_threshold_error) {
    .Call(`_dataprep_mark_outliers_cpp`, x, top, toperr, topmag, bottom, boterr, botmag, use_threshold_error)
}

mark_outliers_matrix_cpp <- function(mat, top, toperr, topmag, bottom, boterr, botmag, use_threshold_error, n_threads = 0L) {
    .Call(`_dataprep_mark_outliers_matrix_cpp`, mat, top, toperr, topmag, bottom, boterr, botmag, use_threshold_error, n_threads)
}

melt_cpp <- function(df, id = NULL, variable_name = NULL, value_name = NULL, major = NULL, as_factor = TRUE, n_threads = 0L, na_rm = FALSE) {
    .Call(`_dataprep_melt_cpp`, df, id, variable_name, value_name, major, as_factor, n_threads, na_rm)
}

na_frac_cpp <- function(x) {
    .Call(`_dataprep_na_frac_cpp`, x)
}

na_runs_cpp <- function(x) {
    .Call(`_dataprep_na_runs_cpp`, x)
}

obsedele_cpp <- function(time_sec, group_int, x, step_sec, half, threshold_sec, n_threads = 0L) {
    .Call(`_dataprep_obsedele_cpp`, time_sec, group_int, x, step_sec, half, threshold_sec, n_threads)
}

quantile_cpp <- function(x, probs) {
    .Call(`_dataprep_quantile_cpp`, x, probs)
}

roll_stats_cpp <- function(x, window, method) {
    .Call(`_dataprep_roll_stats_cpp`, x, window, method)
}

shorvalu_fill_cpp <- function(x, starts, lens, n_threads = 0L) {
    invisible(.Call(`_dataprep_shorvalu_fill_cpp`, x, starts, lens, n_threads))
}

shorvalu_segment_cpp <- function(time_sec, intervals_sec) {
    .Call(`_dataprep_shorvalu_segment_cpp`, time_sec, intervals_sec)
}

snr_cpp <- function(x) {
    .Call(`_dataprep_snr_cpp`, x)
}

transform_elem_cpp <- function(x, method, lambda = 1.0) {
    .Call(`_dataprep_transform_elem_cpp`, x, method, lambda)
}

transform_scale_cpp <- function(x, method) {
    .Call(`_dataprep_transform_scale_cpp`, x, method)
}

winsorize_cpp <- function(x, top, bottom) {
    .Call(`_dataprep_winsorize_cpp`, x, top, bottom)
}

